import React from "react";
import Link from "next/link";
import Head from "next/head";

import fs from "fs";
import matter from "gray-matter";
import md from "markdown-it";

export async function getStaticPaths() {
  // get slugs
  const files = fs.readdirSync("posts");
  const paths = files.map((filename) => ({
    params: {
      slug: filename.replace(".md", ""),
    },
  }));

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params: { slug } }) {
  // get content for each blog

  const mdfile = fs.readFileSync(`posts/${slug}.md`);
  const { data: frontMatter, content } = matter(mdfile);

  return {
    props: {
      frontMatter,
      content,
    },
  };
}

function BlogPage({ frontMatter, content }) {
  return (
    
    <div className="max-w-2xl mx-auto md:max-w-2xl mb-10">
       <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
      <div className='p-2'>
      <article
        className='px-2 prose text-base'
        dangerouslySetInnerHTML={{ __html: md().render(content) }}
      />
    </div>
      </main>
    </div>
  );
}

export default BlogPage;
