import React from "react";
import Link from "next/link";
import Head from "next/head";

import fs from "fs";
import matter from "gray-matter";
import md from "markdown-it";
import Toggle from "../../components/Toggle";

export async function getStaticPaths() {
  // get slugs
  const files = fs.readdirSync("posts");
  const paths = files.map((filename) => ({
    params: {
      slug: filename.replace(".md", ""),
    },
  }));

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params: { slug } }) {
  // get content for each blog

  const mdfile = fs.readFileSync(`posts/${slug}.md`);
  const { data: frontMatter, content } = matter(mdfile);

  return {
    props: {
      frontMatter,
      content,
    },
  };
}

function BlogPage({ frontMatter, content }) {
  return (
    
    <div className="max-w-2xl mx-auto md:max-w-2xl mb-10">
       <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className="flex justify-between bg-gray-50 dark:bg-coolnight-100 p-4 dark:border-moodytext-100 border-b"> 
      <div className="left-0 top-0">
            <Link href="/" passHref>
              <a>
               <div className="cursor-pointer">
                  <h3 className="font-bold text-greytext-100">blog.page</h3>
               </div>
               </a>
            </Link>
          </div>
       <div className="order-last">
       <Toggle />
       </div>
       </nav>

      <main>
      <div className='p-2'>
      <article
        className='px-2 prose text-base'
        dangerouslySetInnerHTML={{ __html: md().render(content) }}
      />
    </div>
      </main>
    </div>
  );
}

export default BlogPage;
