import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Toggle from "../components/Toggle";

import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";

export default function Blog({ posts }) {
  
  return (
    <div className="max-w-md mx-auto lg:max-w-2xl mb-10">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className="flex justify-between p-10"> 

        <div className="text-3xl font-black left-0 top-0">
        <h1>
          Blog
        </h1>
        </div>


       <div className="order-last">
     
       <Toggle />
     
       </div>

       </nav>

      <div className="flex justify-between p-10">
      <span></span>
          <div className="order-last">
            <Link href="/" passHref>
              <a>
               <div className="cursor-pointer">
                  <h1 className="font-bold">About</h1>
               </div>
               </a>
            </Link>
          </div>
      </div>
      
      <main>
          <br></br>
          <br></br>
        <div className='px-10'>
          {posts?.map((post) => {
            return (
              
              <div  key={`${post.slug}`} href={`/blog/${post.slug}`}>
                  <div className='mb-4'>
                    <h1 className='text-2xl font-semibold'>{post.frontMatter.title}</h1>                   
                    <h1 className="font-base h-10 text-gray-500">{post.frontMatter.date}</h1>
                    <p>{post.frontMatter.metaDesc}</p>
                    <Link key={`${post.slug}`} href={`/blog/${post.slug}`}>
                      <a>
                    <h1 className="hover:text-blue-500 text-gray-500 underline">{post.frontMatter.fullContent}</h1>
                    </a>
                    </Link>
                    <div className="flex justify-end">
                    <h1 className="text-gray-500">{post.frontMatter.readTime}</h1>
                    </div>
                  </div>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
    // get the post
    const files = fs.readdirSync("posts");
    const posts = files.map((filename) => {
      const slug = filename.replace(".md", "");
      const readFiles = fs.readFileSync(`posts/${filename}`);
      const { data: frontMatter } = matter(readFiles);
  
      return {
        slug,
        frontMatter,
      };
    });
  
    return {
      props: {
        posts,
      },
    };
  }