import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import Toggle from "../components/Toggle";
import { ArrowLongRightIcon } from "@heroicons/react/24/outline";
import Socials from "../components/Socials";


 const Home = () => {
  
  return (
    <div className="max-w-md mx-auto lg:max-w-2xl mb-10">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className="flex justify-between p-10"> 

      <div className="left-0 top-0">
      <Link href="/blog" passHref>
      <a>
        <div className="cursor-pointer">
          <h1 className="font-bold">Blog</h1>
        </div>
      </a>
      </Link>
      </div>

       <div className="order-last">    
       <Toggle />    
       </div>

       </nav>

       <div className="flex justify-between p-10">
       <div className="text-6xl font-black left-0 top-0">
        <h1>
          VICTOR
        </h1>
        <h1>
          ENO 
        </h1>
        <Socials />
        </div>
        </div>

      <main className="px-10">

          <br></br>

          <div>
          
          <div>
          
             <p>
              Welcome to my home page on the internet. I am a programmer with a restless 
              commitment to exploring ways to fully comprehend the imaginative art of 
              programming for crafting useful and industrial value software 
              applications. My key interests are in open source software, Distributed system,
               Storage, Web servers technology, User interface design
             </p>
          </div>

          </div>

      </main>

     
    </div>
  );
}
export default Home;
