import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import Toggle from "../components/Toggle";
import { ArrowLeftIcon } from "@heroicons/react/24/outline";


 const Projects = () => {
  
  return (
    <div className="max-w-md mx-auto lg:max-w-2xl mb-10">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className="flex justify-between p-10 p-2 m-2">
      <Link href="/" passHref>
      <a>
        <div className="cursor-pointer">
          <ArrowLeftIcon className="h-6 w-12 font-bold" />
        </div>
      </a>
      </Link>

      <div className="order-last">
        <Toggle />
        </div>
        
     </nav>

      <main>
        <div className='p-10'>
           <div className="text-2xl font-semibold">
           A task history on things I'm working on
            </div>      
        </div>
      </main>
    </div>
  );
}
export default Projects;
