import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import Toggle from "../components/Toggle";


 const Projects = () => {
  
  return (
    <div className="max-w-md mx-auto lg:max-w-2xl mb-10">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className="flex justify-between p-10">

        <div className="text-4xl font-black top-0">
        <h1 className="dark:text-blue-200">
          Work Log
        </h1>
        </div>

        <div className="order-last">
        <Toggle />
        </div>

      </nav>


      <div className="flex justify-between p-10">
      <span></span>  
      <div className="order-last">
      <Link href="/blog" passHref>
      <a>
        <div className="cursor-pointer">
          <h1 className="text-black dark:text-blue-200 font-bold">Blog</h1>
        </div>
      </a>
      </Link>
      </div>
      </div>


      <main>
        <div className='px-10 dark:text-blue-200'>
           <div>projects page</div>      
        </div>
      </main>
    </div>
  );
}
export default Projects;
